# Generated by Django 4.2.17 on 2024-12-25 05:10

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Заголовок поста",
                max_length=255,
                validators=[content.validators.validate_title],
            ),
        ),
    ]
